"""
contains the install song logic

basecode generated by claude, i added on top of it
"""

# from pathlib import Path
import yt_dlp
from yt_dlp.utils import DownloadError


sample_track_url = "https://youtu.be/VsiaEw9KOLw?si=W3p54aOwuknwIiK2"

DEFAULT_OUT_DIR="/home/wd/projects/my-utils/music_utility/downloads"
DEFAULT_TEMP_DIR="/home/wd/projects/my-utils/music_utility/downloads/temp"

def download_audio(url, out_dir=DEFAULT_OUT_DIR, temp_out_dir=DEFAULT_TEMP_DIR, codec="mp3", quality="192", playlist=False):
    """Download audio from `url`. Returns a list of final file paths."""
    opts = {
        "format": "bestaudio/best",
        "paths": {
            "home": out_dir,  # where the audio file will end up
            "temp": temp_out_dir  # while downloading it creates a bunch of temp files
        },
        "outtmpl": "%(title|NO_TITLE).150B [%(id)s].%(ext)s",   # .150B = cap title at 150 bytes
        "windowsfilenames": True,     # safe filenames on every OS
        "noplaylist": not playlist,   # URL with video+list -> just the video
        "writethumbnail": True,       # needed for EmbedThumbnail
        # stuff that happens after download, in order top to bottom
        # each key record is the name of the postprocess action
        # everything else is a value
        "postprocessors": [
            {"key": "FFmpegExtractAudio", "preferredcodec": codec, "preferredquality": quality},
            {"key": "FFmpegMetadata", "add_metadata": True},   # title/artist/date tags
            {"key": "EmbedThumbnail"},                         # cover art
        ],
        # The Python API does NOT share the CLI defaults (retries=0 in API vs 10 in CLI):
        "retries": 10, "fragment_retries": 10, "socket_timeout": 20,
        # "quiet": True, 
        "quiet": False,  # outputs a lot of logs to terminal, usefull for debug
        "no_warnings": False,
    }
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=True)
    except DownloadError as e:
        raise RuntimeError(f"yt-dlp failed: {e}") from e

    # here info contains a dict of a lot of metadata of the video, almost everything you might need

    entries = info.get("entries") or [info]  # playlist -> many, video -> one
    return [d["filepath"] for e in entries if e for d in e.get("requested_downloads", [])]


print(download_audio(sample_track_url))

