"""
contains the install song logic

basecode (download_audio) generated by claude, i added on top of it

the use of literals here is caused by the yt_dlp module, its not my bad coding principles or my bad design
"""

# from pathlib import Path
import yt_dlp
from yt_dlp.utils import DownloadError
from dataclasses import dataclass


sample_track_url = "https://youtu.be/VsiaEw9KOLw?si=W3p54aOwuknwIiK2"

DEFAULT_OUT_DIR="/home/wd/projects/my-utils/music_utility/downloads"
DEFAULT_TEMP_DIR="/home/wd/projects/my-utils/music_utility/downloads/temp"


@dataclass
class DownloadReturnMetadata:
    title: str
    filepath: str
    # in future thumbnail, channel name, views and idk other stuff


def fetch_url(url: str, out_dir=DEFAULT_OUT_DIR, temp_out_dir=DEFAULT_TEMP_DIR, download=False, 
                codec="mp3", quality="192", playlist=False, output_name: str="") -> list[DownloadReturnMetadata]:
    """fetches the url, and returns an array of entries that you can work on in future

    Args:
        url (str): url of the video
        out_dir (str, optional): where to download the audio (if download true). Defaults to DEFAULT_OUT_DIR.
        temp_out_dir (str, optional): where to write temp files (skip this one, they are still deleted). Defaults to DEFAULT_TEMP_DIR.
        download (bool, optional): to download the video audio file. Defaults to False.
        codec (str, optional): what type to save&||convert the file to. Defaults to "mp3".
        quality (str, optional): quality of the audio/bitrate. Defaults to "192".
        playlist (bool, optional): whether it is a playlist?. Defaults to False.
        output_name (str, optional): with what name to save the file. Defaults to empty str.

    Raises:
        RuntimeError: on a faild download
        TODO: make it return a null state for song, not throw

    Returns:
        list: a list of entries containing a lot of metatada
    """
    opts = {
        "format": "bestaudio/best",
        "paths": {
            "home": out_dir,  # where the audio file will end up
            "temp": temp_out_dir  # while downloading it creates a bunch of temp files
        },
        # .150B = cap title at 150 bytes
        "outtmpl": f"{'%(title|NO_TITLE).150B [%(id)s]' if not output_name else output_name}.%(ext)s",
        "windowsfilenames": True,     # safe filenames on every OS
        "noplaylist": not playlist,   # URL with video+list -> just the video
        "writethumbnail": True,       # needed for EmbedThumbnail
        # stuff that happens after download, in order top to bottom
        # each key record is the name of the postprocess action
        # everything else is a value
        "postprocessors": [
            {"key": "FFmpegExtractAudio", "preferredcodec": codec, "preferredquality": quality},
            {"key": "FFmpegMetadata", "add_metadata": True},   # title/artist/date tags
            {"key": "EmbedThumbnail"},                         # cover art
        ],
        # The Python API does NOT share the CLI defaults (retries=0 in API vs 10 in CLI):
        "retries": 10, "fragment_retries": 10, "socket_timeout": 20,
        # "quiet": True, 
        "quiet": False,  # outputs a lot of logs to terminal, usefull for debug
        "no_warnings": False
    }
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=download)
    except DownloadError as e:
        raise RuntimeError(f"yt-dlp failed: {e}") from e

    # here info contains a dict of a lot of metadata of the video, almost everything you might need

    entries = info.get("entries") or [info]  # playlist -> many, video -> one

    # TODO: idk how to make this more pythonic
    res = []
    for entry in entries: 
        title = entry["title"]
        path = f"{out_dir}/{output_name}.{codec}" if output_name else ""
        if download and entry:
            for downloaded_file in entry.get("requested_downloads", []):
                path = downloaded_file["filepath"] if downloaded_file and path else ""
        res.append(DownloadReturnMetadata(title=title, filepath=path))

    return res



